ci: Merge test and test-container jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,8 +67,14 @@ jobs:
       matrix: ${{ fromJSON(needs.prepare.outputs.test-matrix) }}
     runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
     timeout-minutes: 60
+    container: ${{ matrix.container && fromJSON(format('{{"image":"{0}","options":"--privileged"}}', matrix.container)) || '' }}
     steps:
       - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
+      - run: |
+          apt-get -o Acquire::Retries=10 -qq update
+          apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends gcc libc6-dev
+          # apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends moreutils
+        if: matrix.container != ''
       - uses: taiki-e/github-actions/free-device-space@1bb80ca038216cd1fb7b6ca6d76240b3772963ab # main # zizmor: ignore[stale-action-refs]
         if: startsWith(matrix.target, 'hexagon')
       # - run: sudo apt-get -o Acquire::Retries=10 -qq update && sudo apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends moreutils
@@ -108,6 +114,7 @@ jobs:
       - uses: taiki-e/setup-cross-toolchain-action@3d9770ce98eb7dbcf378563182a5e8031165f75b # v1.41.0
         with:
           target: ${{ matrix.target }}
+          runner: ${{ matrix.container && 'native' || '' }}
           # TODO(loongarch): wrong result
           qemu: ${{ startsWith(matrix.target, 'loongarch64-') && '10.2' || '' }}
         if: steps.prepare.outputs.target-not-host == 'true' && !startsWith(matrix.target, 'csky-')
@@ -315,8 +322,8 @@ jobs:
         env:
           RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -C target-feature=+thumb-mode
           RUSTFLAGS: ${{ env.RUSTFLAGS }} -C target-feature=+thumb-mode
-        # "LLVM ERROR: underestimated function size" with nightly-2023-08-24
-        if: startsWith(matrix.rust, 'nightly') && (matrix.target == 'armv5te-unknown-linux-gnueabi' || matrix.target == 'armv4t-unknown-linux-gnueabi') && !startsWith(matrix.rust, 'nightly-2023')
+        # "LLVM ERROR: underestimated function size" with old nightly
+        if: startsWith(matrix.rust, 'nightly') && (matrix.target == 'armv5te-unknown-linux-gnueabi' || (matrix.target == 'armv4t-unknown-linux-gnueabi' && !startsWith(matrix.rust, 'nightly-2024') && !startsWith(matrix.rust, 'nightly-2025') && !startsWith(matrix.rust, 'nightly-2026-01'))) && !startsWith(matrix.rust, 'nightly-2023')
       # powerpc +msync
       - run: tools/test.sh -vv --tests ${TARGET:-} -Z build-std
         env:
@@ -384,261 +391,6 @@ jobs:
 
       - run: cargo minimal-versions build --workspace --no-private --detach-path-deps=skip-exact --all-features ${TARGET:-} ${BUILD_STD:-}
       - run: cargo minimal-versions build --workspace --no-private --detach-path-deps=skip-exact --all-features ${TARGET:-} ${BUILD_STD:-} --direct
-
-  test-container:
-    name: test (${{ matrix.rust }}, ${{ matrix.target }}, ${{ matrix.os }})
-    needs: tidy
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - rust: nightly-2023-08-24 # Rust 1.74, LLVM 17 (oldest version that MaybeUninit register is supported)
-            target: armv4t-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          # - rust: nightly-2024-07-31 # Rust 1.82, LLVM 18
-          #   target: armv4t-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: nightly-2025-02-17 # Rust 1.87, LLVM 19
-          #   target: armv4t-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: nightly-2025-08-06 # Rust 1.91, LLVM 20
-          #   target: armv4t-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: nightly-2026-01-28 # Rust 1.95, LLVM 21
-          #   target: armv4t-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          - rust: nightly
-            target: armv4t-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          - rust: '1.74' # LLVM 17 (oldest version that MaybeUninit register is supported)
-            target: armv5te-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          # - rust: '1.81' # LLVM 18
-          #   target: armv5te-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.86' # LLVM 19
-          #   target: armv5te-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.90' # LLVM 20
-          #   target: armv5te-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.94' # LLVM 21
-          #   target: armv5te-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          - rust: stable
-            target: armv5te-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          # - rust: beta
-          #   target: armv5te-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          - rust: nightly
-            target: armv5te-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          - rust: '1.74' # LLVM 17 (oldest version that MaybeUninit register is supported)
-            target: arm-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          # - rust: '1.81' # LLVM 18
-          #   target: arm-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.86' # LLVM 19
-          #   target: arm-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.90' # LLVM 20
-          #   target: arm-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.94' # LLVM 21
-          #   target: arm-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          - rust: stable
-            target: arm-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          # - rust: beta
-          #   target: arm-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          - rust: nightly
-            target: arm-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-          # We test only one version because we do not have soft-float-specific code and
-          # Armv7-specific code is also tested on hard-float target using multiple versions.
-          # - rust: '1.74' # LLVM 17 (oldest version that MaybeUninit register is supported)
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.81' # LLVM 18
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.86' # LLVM 19
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.90' # LLVM 20
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: '1.94' # LLVM 21
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: stable
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          # - rust: beta
-          #   target: armv7-unknown-linux-gnueabi
-          #   runner: native
-          #   os: ubuntu-24.04-arm
-          #   container: debian:13-slim
-          - rust: nightly
-            target: armv7-unknown-linux-gnueabi
-            runner: native
-            os: ubuntu-24.04-arm
-            container: debian:13-slim
-    runs-on: ${{ matrix.os || 'ubuntu-24.04' }}
-    timeout-minutes: 60
-    container:
-      image: ${{ matrix.container }}
-      options: --privileged
-    steps:
-      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
-      - run: |
-          apt-get -o Acquire::Retries=10 -qq update
-          apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends gcc libc6-dev
-          # apt-get -o Acquire::Retries=10 -o Dpkg::Use-Pty=0 install -y --no-install-recommends moreutils
-      - uses: taiki-e/install-action@e3134ec54b36203e18f2d1e80652058bd078dd91 # v2.77.3
-        with:
-          # 0.4.8 fails with at least nightly-2023-05-09 to nightly-2024-01-05
-          tool: cargo-careful${{ (startsWith(matrix.rust, 'nightly-2023') || startsWith(matrix.rust, 'nightly-2024')) && '@0.4.7' || '' }}
-          fallback: none
-        if: startsWith(matrix.rust, 'nightly') && !(startsWith(matrix.os, 'ubuntu') && contains(matrix.os, '-arm'))
-      - uses: taiki-e/install-action@e3134ec54b36203e18f2d1e80652058bd078dd91 # v2.77.3
-        with:
-          tool: rust@stable
-          fallback: none
-        if: startsWith(matrix.rust, 'nightly') && startsWith(matrix.os, 'ubuntu') && contains(matrix.os, '-arm')
-      - uses: taiki-e/cache-cargo-install-action@417450f3c33ee20393705369577571770643d4c7 # v3.0.7
-        with:
-          # 0.4.8 fails with at least nightly-2023-05-09 to nightly-2024-01-05
-          tool: cargo-careful${{ (startsWith(matrix.rust, 'nightly-2023') || startsWith(matrix.rust, 'nightly-2024')) && '@0.4.7' || '' }}
-        if: startsWith(matrix.rust, 'nightly') && startsWith(matrix.os, 'ubuntu') && contains(matrix.os, '-arm')
-      - uses: taiki-e/install-action@e3134ec54b36203e18f2d1e80652058bd078dd91 # v2.77.3
-        with:
-          tool: rust@${{ matrix.rust }},cargo-hack
-          fallback: none
-      - id: prepare
-        run: |
-          if [[ -z "${TARGET}" ]]; then
-            printf 'matrix.target must be set\n'
-            exit 1
-          fi
-          host="$(rustc -vV | grep -E '^host:' | cut -d' ' -f2)"
-          if [[ "${host}" != "${TARGET}" ]]; then
-            printf 'TARGET=--target=%s\n' "${TARGET}" >>"${GITHUB_ENV}"
-            printf 'target-not-host=true\n' >>"${GITHUB_OUTPUT}"
-          fi
-        env:
-          TARGET: ${{ matrix.target }}
-      - uses: taiki-e/setup-cross-toolchain-action@3d9770ce98eb7dbcf378563182a5e8031165f75b # v1.41.0
-        with:
-          target: ${{ matrix.target }}
-          runner: ${{ matrix.runner }}
-        if: steps.prepare.outputs.target-not-host == 'true'
-      - run: |
-          target_lower="${TARGET//-/_}"
-          target_lower="${target_lower//./_}"
-          target_upper=$(tr '[:lower:]' '[:upper:]' <<<"${target_lower}")
-          flags=''
-          if [[ "$(eval "printf '%s\n' \${CARGO_TARGET_${target_upper}_RUNNER:-}")" == *"qemu"* ]]; then
-            flags+=" --cfg qemu"
-          fi
-          if [[ -n "${FLAGS}" ]]; then
-            flags+=" ${FLAGS}"
-          fi
-          if [[ "${RUST}" == "nightly" ]]; then
-            flags+=" -D linker_messages"
-          fi
-          if [[ -n "${flags}" ]]; then
-            printf 'RUSTFLAGS=%s\n' "${RUSTFLAGS}${flags}" >>"${GITHUB_ENV}"
-            printf 'RUSTDOCFLAGS=%s\n' "${RUSTDOCFLAGS}${flags}" >>"${GITHUB_ENV}"
-          fi
-        env:
-          TARGET: ${{ matrix.target }}
-          FLAGS: ${{ matrix.flags }}
-          RUST: ${{ matrix.rust }}
-
-      - run: tools/test.sh -vv ${TARGET:-} ${DOCTEST_XCOMPILE:-} ${BUILD_STD:-}
-      # We test doctest only once with the default build conditions because doctest is slow.
-      # src/tests has extended copies of doctest, so this will not reduce test coverage.
-
-      # arm v8 little endian
-      - run: tools/test.sh -vv --tests ${TARGET:-} ${BUILD_STD:-}
-        env:
-          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -C target-feature=+v8
-          RUSTFLAGS: ${{ env.RUSTFLAGS }} -C target-feature=+v8
-        if: startsWith(matrix.target, 'armv7') || startsWith(matrix.target, 'thumbv7')
-      # arm v6 legacy cp15_barrier
-      - run: tools/test.sh -vv --tests ${TARGET:-} ${BUILD_STD:-}
-        env:
-          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} --cfg atomic_maybe_uninit_use_cp15_barrier
-          RUSTFLAGS: ${{ env.RUSTFLAGS }} --cfg atomic_maybe_uninit_use_cp15_barrier
-        if: matrix.target == 'arm-unknown-linux-gnueabi'
-      # arm pre-v6 thumb
-      - run: tools/test.sh -vv --tests ${TARGET:-} -Z build-std
-        env:
-          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -C target-feature=+thumb-mode
-          RUSTFLAGS: ${{ env.RUSTFLAGS }} -C target-feature=+thumb-mode
-        # "LLVM ERROR: underestimated function size" with old nightly
-        if: startsWith(matrix.rust, 'nightly') && (matrix.target == 'armv5te-unknown-linux-gnueabi' || (matrix.target == 'armv4t-unknown-linux-gnueabi' && !startsWith(matrix.rust, 'nightly-2024') && !startsWith(matrix.rust, 'nightly-2025') && !startsWith(matrix.rust, 'nightly-2026-01'))) && !startsWith(matrix.rust, 'nightly-2023')
 
   build:
     name: build (${{ matrix.name || matrix.rust }})
